#	Copyright (c) 1988 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)libelf:m32/makefile	1.15"

#	machine dependent values

MACH=		m32
MACHNM=		M32

include ../common/Makefile
