#	Copyright (c) 1988 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)sdb:libmachine/m32/makefile	1.4"

TARGET = $(PRODLIB)/libmachine.a

include ../../util/std.make

CCSOURCES = \
	Instr.C

include DEPEND

include ../../util/lib.make
