./"	Copyright (c) 1988 AT&T
./"	All Rights Reserved 
./"	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
./"	The copyright notice above does not evidence any 
./"	actual or intended publication of such source code.
./"
.TH RAIN 6
.SH NAME
rain \- animated raindrops display
.SH SYNOPSIS
rain
.SH DESCRIPTION
.PP
.ad b
.IR Rain 's
display is modeled after the VAX/VMS program of the same name.
The terminal has to be set for 9600 baud to
obtain the proper effect.
.PP
As with all programs that use
.IR termcap ,
the TERM environment
variable must be set (and exported) to the type of the terminal being used.
.SH FILES
/etc/termcap
.SH AUTHOR
Eric P. Scott
