/*	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ident	"@(#)lp:lib/lpNet/_xdrMsgs.c	1.2"
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "_xdrMsgs.h"

bool_t
xdr_physicalMsgTag(xdrs, objp)
	XDR *xdrs;
	physicalMsgTag *objp;
{
	if (!xdr_long(xdrs, &objp->physicalMsgSize)) {
		return (FALSE);
	}
	return (TRUE);
}
