#	Copyright (c) 1984 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)sti:demo/makefile	1.2"

install:
		cpset form0.c $(ROOT)/usr/src/lib/eti/demo 644 bin bin
		cpset form1.c $(ROOT)/usr/src/lib/eti/demo 644 bin bin
		cpset form2.c $(ROOT)/usr/src/lib/eti/demo 644 bin bin
		cpset menu0.c $(ROOT)/usr/src/lib/eti/demo 644 bin bin
		cpset menu1.c $(ROOT)/usr/src/lib/eti/demo 644 bin bin
