#	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)oamintf:networks/Makefile	1.5"

O_DFILES=\
	networks.menu

all :

clean: 

clobber: clean

size strip: all
	:

install: all xinstall

PROTO=../Prototype
OBJECTS=$(O_DFILES)
include ../Install
