#	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)localedef:datetbl/datetbl.mk	1.1"

#	Makefile for datetbl

ROOT =

INS = install

DIR = $(ROOT)/usr/bin

INC = $(ROOT)/usr/include

LDFLAGS = -s $(SHLIBS)

CFLAGS = -O -I$(INC) 

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = datetbl.mk

MAINS = 

OBJECTS =  

SOURCES = 

ALL:		$(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL 
	$(INS) -f  $(ROOT)/usr/lib/locale/C LC_TIME

